<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Health  Beauty</name>
   <tag></tag>
   <elementGuidId>87250b09-9e88-4768-8a52-158c926bec6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#health-and-beauty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='health-and-beauty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Health &amp; Beauty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe829763-8739-496d-8bf0-f39341709fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/health-and-beauty</value>
      <webElementGuid>eb0152a9-3fb7-46bd-935a-b51709224d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>health-and-beauty</value>
      <webElementGuid>aebb2f67-e86a-49f3-a94d-f6e5ecc12520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>3d522467-ffb6-435d-8b71-4826bece780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fc5d92a-806d-4752-b366-8b0ab19d2f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>2d2cd138-66aa-4aaa-a647-e57efc9cc5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07c1a5cb-a417-4d7d-9e0a-ebc7dae6861b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96363dde-ae39-4204-8e0b-0a5aa598b3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b58da27-fd6e-4764-85ff-d5f361b0eaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Health &amp; Beauty</value>
      <webElementGuid>fd1ac3ca-106e-4d00-a589-99dcc56ec4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health-and-beauty&quot;)</value>
      <webElementGuid>5649cd66-f089-445e-a3e7-f20b232e95e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='health-and-beauty']</value>
      <webElementGuid>7b51bad5-ebdb-4bf8-bcbd-2851b472a2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-navbar-collapse']/div/div/nav/div[2]/ul/li[11]/a</value>
      <webElementGuid>19b81b6c-1b7e-477a-a41b-08c8fbc2e30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Health &amp; Beauty')])[2]</value>
      <webElementGuid>bed657d6-3435-46c1-b868-62eaa64c5214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homesmart'])[1]/following::a[2]</value>
      <webElementGuid>6b717dad-4e80-494c-8989-cdfc99596648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Under 20'])[1]/following::a[3]</value>
      <webElementGuid>54a15a07-2cab-4f2d-a43b-9d1952fcd77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nail Care'])[1]/preceding::a[1]</value>
      <webElementGuid>69040960-b2be-4a69-bb2d-d9302f3e9cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hair Care'])[1]/preceding::a[2]</value>
      <webElementGuid>89072f4f-a2d7-45d8-9919-b1fb8d84434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/health-and-beauty')]</value>
      <webElementGuid>7414048e-f5e3-4293-8fab-c5b71154ce71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>e59826e7-2aed-404d-8942-8822167898b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/health-and-beauty' and @id = 'health-and-beauty' and (text() = 'Health &amp; Beauty' or . = 'Health &amp; Beauty')]</value>
      <webElementGuid>561bfba5-eaf3-4733-b4af-07a7c5079f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
