<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>FPC_01_02-health cart_Testsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9d1d41cd-a35f-4b8a-97da-2048bc4523e2</testSuiteGuid>
   <testCaseLink>
      <guid>c1d1c562-e407-4b6f-8115-f77ae6ca2c76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PDL test/FPC -01 __heathcart __Add to cart__place order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d19597ba-0173-43b2-b2ca-7c2d0be91e2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a11984f2-f7fd-440d-8d84-b81cb1d5cc3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c865972d-7bf3-4d4d-85df-c5b0df991c5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PDL test/FPC-02_Healthcart_ quickcart_place order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dbf1976-8d9f-4826-9ee5-cf5b2724abdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b50d7e-4fa5-47c4-abf7-356d14eedf90</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
