<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Pay with PayPal</name>
   <tag></tag>
   <elementGuidId>27fd23fd-ee5a-4b1f-9150-fe6ecc33f4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headerText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='headerText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Pay with PayPal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>27a62ead-14d3-4926-a905-334a48d53a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headerText</value>
      <webElementGuid>ef3b3a4e-c0f9-40c5-a7dc-cfb9f3b47c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerText  </value>
      <webElementGuid>f5999779-9208-4aef-a09a-86579eb15a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay with PayPal</value>
      <webElementGuid>8ee58d0e-2f4f-4402-9749-2100c4186e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerText&quot;)</value>
      <webElementGuid>9403075b-4d79-469d-b528-05c3e68edfbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='headerText']</value>
      <webElementGuid>92dd17a4-7266-4a93-aa4b-b80523c1f9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/h1</value>
      <webElementGuid>caa6cb92-910b-45aa-8751-9d02fd6357f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See terms'])[1]/preceding::h1[1]</value>
      <webElementGuid>0e8d8f00-963f-4848-9580-f450cec668af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose your phone country code'])[1]/preceding::h1[1]</value>
      <webElementGuid>ddcae981-2373-4561-8a0a-54f9e90fce3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay with PayPal']/parent::*</value>
      <webElementGuid>bd504468-c972-4a63-961a-edaa4bcb1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>55e34bf3-a6cb-4c0e-846f-a7764122fa23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'headerText' and (text() = 'Pay with PayPal' or . = 'Pay with PayPal')]</value>
      <webElementGuid>2435ba9e-963b-48f5-97c8-07e9c862c49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
