<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Refine by Style fragrance_tile-image productTileImage</name>
   <tag></tag>
   <elementGuidId>ef7158ba-0f73-47ad-95b5-f033ac648820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.tile-image.productTileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8684c5cc-a19b-4103-940b-32290572e846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage</value>
      <webElementGuid>c2b4fd4d-cdf7-4751-baa6-ea2ad3decefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>4a28c075-98fa-4e66-ba59-ead2d263ddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>ca83cc3f-f50a-41e4-9780-f02b55c6a6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681.jpg?w=300&amp;h=300</value>
      <webElementGuid>d0c8abf8-84f7-4873-8363-f31800e4a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw475e4155/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>56fafa91-353a-4279-bb8f-8a6e01b74351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)</value>
      <webElementGuid>7ddfbbdd-33ba-44f8-818d-c47253eef9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)</value>
      <webElementGuid>40f10f70-1912-433a-85de-2779ba39f654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-9 col-xl-10&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-3 product-tile-wrapper&quot;]/div[@class=&quot;product product-listItem&quot;]/div[@class=&quot;product-tile general-tile&quot;]/div[@class=&quot;product-image-tile-body&quot;]/div[@class=&quot;image-container&quot;]/a[1]/img[@class=&quot;tile-image productTileImage&quot;]</value>
      <webElementGuid>c8e90c6e-7229-4707-997b-3055eb268c03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>edae9dfd-7618-4cc1-9f22-8dabd313a2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)']</value>
      <webElementGuid>b496e333-9304-4f89-9c3b-2f71f3c29227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>9da8899e-3587-49b6-9f77-9a751b86ecf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300' and @alt = 'The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)' and @title = 'The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)']</value>
      <webElementGuid>f68d8f52-b375-4dce-8629-26bcdad55c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
