<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Phone Number_loginEmail</name>
   <tag></tag>
   <elementGuidId>b9ca3576-6b3c-4605-bd46-e8bb5604c96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form-email-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form-email-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email or Phone Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c92a9c5c-30f5-42b3-bd0c-929dff512864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8226990f-68dd-4ab1-b4b4-c334c03039a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form-email-phone</value>
      <webElementGuid>00830d31-3cec-4aca-b1b4-5e5c34a084b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1af7ac2e-204e-4393-8f87-fb01ab62efce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>411a0b10-0e82-4120-a86c-062fc3230cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Please enter Email or Phone Number</value>
      <webElementGuid>8d09ecef-f476-46b0-8c84-f9bfdc7d3d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>form-email-error</value>
      <webElementGuid>647e4f43-db75-4bb4-bda7-393fdfe81d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginEmail</value>
      <webElementGuid>a41b5ef6-0456-485f-9192-c7d5edfe1568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-email-phone&quot;)</value>
      <webElementGuid>b2fd3ac7-5aa2-4220-9ff4-68c3b082a895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form-email-phone']</value>
      <webElementGuid>68c63b54-dc6d-43df-8906-54bdba9f102d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/input</value>
      <webElementGuid>bf2e06d8-5cc5-4ea5-874a-b07db9eb9ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>2fcef9ef-d0ec-447b-b00e-c8e47f9c2efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'login-form-email-phone' and @name = 'loginEmail']</value>
      <webElementGuid>b8361f85-27a1-4a0e-a247-19638dcc128e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
