<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy Now</name>
   <tag></tag>
   <elementGuidId>8ba34b8e-d942-419a-a8ee-778ad210ed4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='continueToCheckout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#continueToCheckout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#continueToCheckout</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4c3cc17-5fc9-4371-93fb-672009f3bcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToCheckout</value>
      <webElementGuid>afda76e7-0015-4ee7-bcd9-4993095ce262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>livetv-add-to-cart </value>
      <webElementGuid>12f34fad-5507-49cf-8cb8-32118b2c2c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>/on/demandware.store/Sites-SHOP_LC-Site/en_US/Checkout-Login?cartType=normalproducts&amp;isLivetvCheckout=true</value>
      <webElementGuid>391a516a-946d-41f8-874a-24934cd5c801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>119.99</value>
      <webElementGuid>0cbe1beb-a23e-4d43-873e-4a8a4287ea2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brand</name>
      <type>Main</type>
      <value>Shop LC</value>
      <webElementGuid>02b941a3-44a4-451b-ba8c-77a96f0b41f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>$1</value>
      <webElementGuid>c2b82340-b160-407b-bb7b-83c735939c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Buy Now
            </value>
      <webElementGuid>588fa652-9049-4264-aad7-d1ada5253aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToCheckout&quot;)</value>
      <webElementGuid>247b60db-4db2-4344-834c-dbddd46e46a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='continueToCheckout']</value>
      <webElementGuid>8840c0bb-132f-4b3d-b1fe-e2527eb94a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[5]/a</value>
      <webElementGuid>6869b32d-ecf2-4b6a-af06-7c088f29b10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/following::a[1]</value>
      <webElementGuid>ae3fcc45-da56-4ad9-8c43-0fddea091c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAST BUY'])[1]/preceding::a[1]</value>
      <webElementGuid>8513c353-af0b-480e-a4f4-7daad2afe187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>d934350d-be01-4e2c-a616-be375f1e7f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'continueToCheckout' and (text() = '
                Buy Now
            ' or . = '
                Buy Now
            ')]</value>
      <webElementGuid>917cdae0-6588-4731-bcf3-773ee83fc220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
