<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Next auction is loading_selectedProductImage</name>
   <tag></tag>
   <elementGuidId>f88bc24b-d05a-4e9e-9127-3eaa318e2ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='selectedProductImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedProductImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Quick View for Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87bb0002-4153-4866-ba46-188bf118487a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedProductImage</value>
      <webElementGuid>6a977987-b3df-4f02-9a0e-76458cfe5dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage lazyloaded</value>
      <webElementGuid>195fd97e-0e63-45d9-af59-9ff21061a67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/72/4/7247668/7247668.jpg?w=300&amp;h=300</value>
      <webElementGuid>44f9e0f5-8fe4-4ca2-a4cb-f8d54d922d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/72/4/7247668/7247668_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>bed7166a-d0ee-44ff-9e54-5dc7f623b009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/72/4/7247668/7247668.jpg?w=300&amp;h=300</value>
      <webElementGuid>b9023e23-4837-4408-a87f-1fe3a0fad1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw6837cb0f/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>d7865ac2-6c2c-486e-b224-7c22ab359aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone</value>
      <webElementGuid>a19328b5-0e7e-4dae-99cd-5c1fb19e16af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/72/4/7247668/7247668_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>0b410057-68d0-465b-be4f-ae03a5ef19ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedProductImage&quot;)</value>
      <webElementGuid>7bd7644c-9c3b-436b-8d0b-7338117c9a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='selectedProductImage']</value>
      <webElementGuid>b883f4f5-d005-4ec3-b691-33adb776cb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div/div[2]/div/a/img</value>
      <webElementGuid>cd0afcfc-781e-4f0c-9b4d-5edd7157aef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone']</value>
      <webElementGuid>60943843-334f-4a89-b19f-e9ce8e8b1da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a/img</value>
      <webElementGuid>4fe4259d-1b5d-43d9-b744-21745e9bfc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'selectedProductImage' and @alt = 'Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone' and @src = 'https://image.shoplc.com/products/72/4/7247668/7247668_1.jpg?w=300&amp;h=300']</value>
      <webElementGuid>5e627a98-1555-4b85-9b9d-adadd2e3d370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
