<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select optionGoldtone ( 119.99 )Rose_df4d96</name>
   <tag></tag>
   <elementGuidId>942252dc-8bfc-4332-b2fb-69cd380d3c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='attributeGroup-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attributeGroup-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeGroup-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd05cee4-099a-4c35-a70e-4db2b795ed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d9c220cf-773b-485a-9fcb-421ee9f67952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attributeGroupSelector</value>
      <webElementGuid>e8b98dce-2a74-4584-8743-a0a15fe796e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeGroup-0</value>
      <webElementGuid>ee3b6b2f-c164-41db-b936-2d56570a39f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute-group-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56c58caf-64df-4fae-baf6-6cbb76019a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )</value>
      <webElementGuid>95dbe61d-c412-4612-baa7-260a0eea5db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeGroup-0&quot;)</value>
      <webElementGuid>7048158e-31b4-4365-998c-9680b0fd937b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='attributeGroup-0']</value>
      <webElementGuid>a8cdc987-3aa2-4f49-90cd-f5b1cbf53cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[4]/div/select</value>
      <webElementGuid>b6b77ebe-c8a6-4cae-8387-4e233fe334e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone'])[1]/following::select[1]</value>
      <webElementGuid>962b3456-1945-40c5-87f7-e518950e5d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/preceding::select[1]</value>
      <webElementGuid>469c3d86-6539-42fb-85d5-cc92dc43bac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::select[1]</value>
      <webElementGuid>ecb5144a-c5ce-4241-89f8-28aac4e2eb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2b344d7b-7ae1-4e26-a87f-95026f5d3432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'attributeGroupSelector' and @id = 'attributeGroup-0' and (text() = 'Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )' or . = 'Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )')]</value>
      <webElementGuid>78954440-1cda-468e-afb3-0229f697c545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
