<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ADD NEW PAYMENT</name>
   <tag></tag>
   <elementGuidId>dbede68f-aa3a-467f-97cf-18dd81971f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;ADD NEW PAYMENT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22570b3a-debf-4ada-bb0f-685f8133779a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>36fc54e2-7140-4b18-94c6-8418d8cb581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>c6119f38-1ac4-4e30-9a9b-ee20bcbbf72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save btn-block save-payment btn-navy-blue</value>
      <webElementGuid>df6aef79-8847-460f-95c1-8ac83932feb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD NEW PAYMENT</value>
      <webElementGuid>4431d9a8-8fbd-4eb5-95fb-0b42a6969ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;&quot;dwfrm_creditCard&quot;&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/button[@class=&quot;btn btn-save btn-block save-payment btn-navy-blue&quot;]</value>
      <webElementGuid>34a74e80-ae3e-4a41-a8f7-273e173f3504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='save']</value>
      <webElementGuid>a3a21f11-df9e-4676-a6f5-912e88b5b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='&quot;dwfrm_creditCard&quot;']/div[3]/div/button</value>
      <webElementGuid>b6cf96a6-177c-4a84-95fb-6374cdf16ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/following::button[1]</value>
      <webElementGuid>cafa9bc4-f689-4011-8866-b4be2d18d84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cvv'])[2]/following::button[2]</value>
      <webElementGuid>34210cfd-90ee-40f2-8336-054d2cac5233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/button</value>
      <webElementGuid>b3b9b500-ed4b-480c-8684-9d958e5944fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'save' and (text() = 'ADD NEW PAYMENT' or . = 'ADD NEW PAYMENT')]</value>
      <webElementGuid>af050882-b7d6-4cc1-8592-86f80aa7cfe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
