<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ShopLC Dev_pushengage-opt-in-9-close</name>
   <tag></tag>
   <elementGuidId>3a3fac21-21b9-445c-82af-4c5f81a75d0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pushengage-opt-in-9-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pushengage-opt-in-9-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pushengage-opt-in-9-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09e80786-a297-41d2-ae26-70720ce56a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pushengage-opt-in__sleek-opt-in-box__close-icon</value>
      <webElementGuid>8d3efd66-fe10-4774-b96d-8efa07e6d72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pushengage-opt-in-9-close</value>
      <webElementGuid>9db38d71-e27f-4225-a52f-52f639dd28da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pushengage-opt-in-9-close&quot;)</value>
      <webElementGuid>ba3be3f7-2d5b-4ad1-8f32-f6553dc8a174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-9-close']</value>
      <webElementGuid>d351d7e9-59b7-4596-ad9b-7808b52f176e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-9']/div/div/div[2]</value>
      <webElementGuid>ec36ac8b-ea4d-4913-9158-10f3fb67536a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopLC Dev'])[1]/following::div[1]</value>
      <webElementGuid>0e133410-739d-4add-ad52-b34115cc1fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notify Me'])[1]/preceding::div[5]</value>
      <webElementGuid>9cc90b98-b948-4c65-98fe-f35982d44720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]</value>
      <webElementGuid>1688ecff-9489-4851-89e4-2ecd61a42468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pushengage-opt-in-9-close']</value>
      <webElementGuid>8a2bc73b-a8f6-4b62-9c69-38d2abb2deef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
