<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notify Me_dot2</name>
   <tag></tag>
   <elementGuidId>c23a3a63-a53d-496e-876c-b7d3a0c6416d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dot2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[10]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.dot2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e368062b-08ae-46b7-b0cc-b704b5651f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dot2</value>
      <webElementGuid>c4f7e47b-2eec-4d66-a20f-96528ece88a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;veiled&quot;]/body[1]/div[@class=&quot;veil&quot;]/div[@class=&quot;spinner&quot;]/div[@class=&quot;dot2&quot;]</value>
      <webElementGuid>2a6513dd-b7b3-4b5f-9062-1a90b270efa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[2]</value>
      <webElementGuid>6557e409-9999-4ae4-859d-45ad030ad970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
