<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_year_dwfrm_creditCard_securityCode</name>
   <tag></tag>
   <elementGuidId>b15b3f6b-21b5-4fb0-9455-fc9927eb7913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#securityCodeNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityCodeNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;cvv&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27e46a00-17cf-40fe-bba7-947cc31a082e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a5659cc1-5382-44ce-b84b-3619df55b912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>384fa218-b89c-4e6b-ab3c-c23e08bb65e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce946d8c-17bf-4bfc-8976-b6c309702b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cardSecurityCode securityCode input-custom-orange</value>
      <webElementGuid>3ae52319-9874-429c-abb8-64f5a4261384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityCodeNew</value>
      <webElementGuid>3654a36b-b5de-444b-91c7-8c4a1fc34c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_creditCard_securityCode</value>
      <webElementGuid>3a28b270-b3d8-4a96-b456-fe63a55bbfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8771d0d9-79bb-434e-8eec-de69be8c34d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>109b1464-bd13-46c6-930f-f364c54235eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>0f4e898d-329c-48a2-a71e-66eb23dc5f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>securityCodeInvalidMessage</value>
      <webElementGuid>2ce3f6e8-2b36-494b-84c7-601e5f659037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityCodeNew&quot;)</value>
      <webElementGuid>04e350e7-cb0f-472f-8d9d-a208e29e9631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityCodeNew']</value>
      <webElementGuid>25c1e920-25ad-4b44-8378-b777df5b80f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='&quot;dwfrm_creditCard&quot;']/div[2]/div[3]/div/input</value>
      <webElementGuid>3c41a52e-bd71-4022-b7a2-2b1f869d60e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[3]/div/input</value>
      <webElementGuid>d16358a6-2a5a-4322-8623-3072ed17f558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'securityCodeNew' and @name = 'dwfrm_creditCard_securityCode']</value>
      <webElementGuid>872b9d30-2ad6-43c8-a00b-45ccad61fd60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
