<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_dwfrm_billing_contactInfoFiel_477a34</name>
   <tag></tag>
   <elementGuidId>a13414e6-44e4-4f77-9f8f-c901ca8c44dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkoutGuestEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkoutGuestEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77bff3fc-e331-44f4-9463-4764cdf0bb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dba20c9c-2ac4-4f85-b604-b6e65de75c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a1cc6300-35cc-475b-80b2-fc5b768c101e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom prefilled email is-invalid</value>
      <webElementGuid>15e16f73-f39a-4796-8e92-56ff962dce63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkoutGuestEmail</value>
      <webElementGuid>45d78648-c8b0-4c04-95ec-b64e052854a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-empty-email</name>
      <type>Main</type>
      <value>Please enter your email address before proceeding further</value>
      <webElementGuid>705b7e15-c00b-4d15-a527-bb5cd7174923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-email-invalid</name>
      <type>Main</type>
      <value>Please enter a valid email address.</value>
      <webElementGuid>bd4e27e9-079d-4f0e-8d72-d88dfcf7464e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_billing_contactInfoFields_email</value>
      <webElementGuid>c20312fd-7e62-4b09-8539-053154419478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>07f13765-e619-4c7d-9302-20400b596b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\w.%+\-]+@[\w.\-]+\.[\w]{2,6}$</value>
      <webElementGuid>d60ef92e-cd77-4e87-8a1b-6eaf438037af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailInvalidMessage</value>
      <webElementGuid>328cfa89-56b2-4d37-a9fb-384ccffeeeb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutGuestEmail&quot;)</value>
      <webElementGuid>89935d67-3ce4-40df-ad21-b6aaef2fb0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkoutGuestEmail']</value>
      <webElementGuid>34515bfa-7155-480f-bd16-b389baca50ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-main']/div/div/div[9]/form/div/div/div/input</value>
      <webElementGuid>c836cd40-96aa-4832-940b-ff603afc9dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/form/div/div/div/input</value>
      <webElementGuid>e4cfc03e-63ee-418b-9fe1-a210a5aa21be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email' and @id = 'checkoutGuestEmail' and @name = 'dwfrm_billing_contactInfoFields_email']</value>
      <webElementGuid>a0d3bf72-1604-4798-b4e7-267c2097706d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
