<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_add new card_dwfrm_creditCard_cardOwner</name>
   <tag></tag>
   <elementGuidId>dc6eaaa1-d11c-41d2-b681-bab5bcfd9a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardOwnerNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardOwnerNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Name on Card:&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ec5bcf4-0e1c-493c-95a4-943bad781cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>abc3540c-8d40-488c-99b9-e3c4b34f60cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>975d116b-e43b-4a97-a8f2-6b57c6814d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom-orange</value>
      <webElementGuid>1b46bd5d-8737-4868-9398-83c33a52956a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardOwnerNew</value>
      <webElementGuid>47601da6-91d7-4d6d-acc8-caea9d865545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_creditCard_cardOwner</value>
      <webElementGuid>6c8c44e9-5b03-42fe-b0b6-3d6226c32e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f913975-7244-4d4b-bdd3-a1c63f40f75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>475f94fd-968d-462a-ba21-7d57f9be3dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z ]+$</value>
      <webElementGuid>c85f0603-c83b-4c08-80e8-741fde34d424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-name</value>
      <webElementGuid>be368848-e7bb-4d15-b814-0b3eebd26552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardOwnerNew&quot;)</value>
      <webElementGuid>664b295b-d96b-4f4a-9d71-c728e2bd26b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardOwnerNew']</value>
      <webElementGuid>242fdfaa-1982-47ff-83ac-b26c392b2010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='&quot;dwfrm_creditCard&quot;']/div/div/div/input</value>
      <webElementGuid>a26474fd-0bc0-48e1-b867-b4a23603ebd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/input</value>
      <webElementGuid>0e3b38a5-c9a9-4cec-bf56-bd424c89ac64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cardOwnerNew' and @name = 'dwfrm_creditCard_cardOwner']</value>
      <webElementGuid>640c9e7d-4467-4172-9c5a-5b0212c4f62e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
