<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Remove</name>
   <tag></tag>
   <elementGuidId>f37d81ae-2d0b-43c2-bb12-dfbc13023a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.remove-btn.cart-delete-confirmation-btn.btn.btn-light > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-main']/div/div/div[10]/div[7]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Remove product Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>426c8338-cd04-4f7d-bf3f-34a9065ff809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3902daf0-8369-401f-b89e-180d9b19bcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>0840bd73-ac7e-479e-8dac-027e4c43f78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-main&quot;)/div[@class=&quot;row align-items-sm-start&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;checkout-forms-container&quot;]/div[@class=&quot;cart-items checkout-block checkout-block-items&quot;]/div[@class=&quot;checkout-block-items-container&quot;]/div[@class=&quot;card product-info    uuid-5b2eba4a69fff10b38a76c0f85&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;col-5 col-lg-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xs-8 d-none d-lg-block&quot;]/div[@class=&quot;item-attributes d-flex flex-column&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;d-none d-lg-block qty-rbtn&quot;]/button[@class=&quot;remove-btn cart-delete-confirmation-btn btn btn-light&quot;]/span[1]</value>
      <webElementGuid>c51a7462-8aaa-4cca-b5fa-5066b8b5c155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-main']/div/div/div[10]/div[7]/div[2]/div[2]/div/div/div/div[2]/div/div/div[3]/button/span</value>
      <webElementGuid>6fbf7a16-101d-433a-9021-247feb260a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save for later'])[1]/following::span[1]</value>
      <webElementGuid>ddb9cb7f-1e19-4a13-af00-dc8c8a8705f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>a52c95e0-3b7e-4a27-8327-bab44d844d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>035bd83e-05fd-4b87-a9dc-80fbfca718a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>7b4694d7-5e13-4d12-8a15-15ebaf2ba68b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
