<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Next auction is loading_selectedProductImage</name>
   <tag></tag>
   <elementGuidId>70fda819-64c2-4767-b00a-a6da42c768b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedProductImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='selectedProductImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Quick View for Amethyst Lever Back Earrings in Sterling Silver 0.85 ctw&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7e4d6c36-00c3-4283-848e-b5490834a5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedProductImage</value>
      <webElementGuid>bd50cd50-bfb7-4cb6-9701-49b2aaefff20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage lazyloaded</value>
      <webElementGuid>a30b7548-cdab-4508-91b2-fca12d75757f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/4/7344840/7344840.jpg?w=300&amp;h=300</value>
      <webElementGuid>3d331b38-c8a5-4f18-8262-067d1aca71e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/4/7344840/7344840_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>dbaf675e-1391-4504-b9c4-50a114f02d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/4/7344840/7344840.jpg?w=300&amp;h=300</value>
      <webElementGuid>7267bd27-c045-407b-8848-a944dbf150fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw280fec51/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>78166266-d3ac-43d9-aad8-8d691b7d08c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amethyst Lever Back Earrings in Sterling Silver 0.85 ctw</value>
      <webElementGuid>1bb61d67-1b01-4efa-97ab-72fcec2cbe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/4/7344840/7344840_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>d1db8d11-4cb3-4f73-bf8f-ebbcb8ddec64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedProductImage&quot;)</value>
      <webElementGuid>5f0b5b72-c14c-4ded-bdf3-e75693e8fac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='selectedProductImage']</value>
      <webElementGuid>6dce3260-ec0d-4940-90a3-1aab57581f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div/div[2]/div/a/img</value>
      <webElementGuid>306c1af1-7048-475b-a9ef-5c9e58c09bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amethyst Lever Back Earrings in Sterling Silver 0.85 ctw']</value>
      <webElementGuid>347d8cd0-4819-427b-9c4c-3c0d4d479e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a/img</value>
      <webElementGuid>4ce20408-c6ac-41fe-bd2e-4ef8033846ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'selectedProductImage' and @alt = 'Amethyst Lever Back Earrings in Sterling Silver 0.85 ctw' and @src = 'https://image.shoplc.com/products/73/4/7344840/7344840_1.jpg?w=300&amp;h=300']</value>
      <webElementGuid>45be0226-6190-4797-b327-a540f71d2c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
