<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>7cdc8a93-a106-4fa6-bbec-686efee86494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.page.order-page.page-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div/div/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;2&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7fef6076-dbdc-4093-a84a-d487da3c588b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page order-page page-2</value>
      <webElementGuid>b9eaf166-7b3c-4df2-975e-75d92de65595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev01.shoplc.com/c/health-and-beauty?prefn1=articleType&amp;prefv1=Makeup&amp;start=60&amp;sz=60</value>
      <webElementGuid>c7c3a0f9-9ab8-40bb-a1ed-1ccb2cee5f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                2
                            </value>
      <webElementGuid>0f9e69c0-cf98-4e29-805e-86f751894a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row grid-header&quot;]/div[@class=&quot;result-count d-flex text-center col-12 col-md-10 order-md-3 py-md-0 py-2&quot;]/div[@class=&quot;d-flex col justify-content-center justify-content-lg-start p-0&quot;]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;pagination-page&quot;]/a[@class=&quot;page order-page page-2&quot;]</value>
      <webElementGuid>18a71025-0123-435d-98e5-aa883c382eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>fdf17b28-af2d-425b-b88b-cb0921a2318a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[7]</value>
      <webElementGuid>790c1561-a78a-4272-8485-2f4ee1ece3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health &amp; Beauty'])[3]/following::a[3]</value>
      <webElementGuid>b27ad816-e431-42aa-95f1-f67bd9bb76fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LC'])[1]/following::a[3]</value>
      <webElementGuid>2248fb55-2730-4615-8ee5-3330e6d7e749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last'])[1]/preceding::a[2]</value>
      <webElementGuid>1e3dcd64-ea79-40a3-b58b-2f4b922e8574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::a[3]</value>
      <webElementGuid>572c370a-0ed5-448a-9bf5-3dab2d4033d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>eb74679e-7d0f-4e92-8587-71121713f862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev01.shoplc.com/c/health-and-beauty?prefn1=articleType&amp;prefv1=Makeup&amp;start=60&amp;sz=60')]</value>
      <webElementGuid>6626e1bc-4076-49a2-89f4-09e5c08b5ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/ul/li[2]/a</value>
      <webElementGuid>c5f34de9-f5f9-42dd-ac32-3ab609ab283e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev01.shoplc.com/c/health-and-beauty?prefn1=articleType&amp;prefv1=Makeup&amp;start=60&amp;sz=60' and (text() = '
                                2
                            ' or . = '
                                2
                            ')]</value>
      <webElementGuid>26b758d8-bb8e-4266-a555-c1675bb31393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
