<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Refine by Product Type Health_fa fa-square-o</name>
   <tag></tag>
   <elementGuidId>4b8cd098-606a-4819-bf01-7afec836fa03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='refinement-product-type']/ul/li[2]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Refine by Product Type: Makeup&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>497ad191-8cff-4881-b987-8586f3d7a8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-square-o</value>
      <webElementGuid>b479053d-5ecd-44d4-bf2e-c9d3c87633bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refinement-product-type&quot;)/ul[@class=&quot;values content&quot;]/li[@class=&quot;col-sm-4 col-md-12 pr-md-0&quot;]/button[@class=&quot;pr-md-0&quot;]/i[@class=&quot;fa fa-square-o&quot;]</value>
      <webElementGuid>9e4872ff-ce3d-4035-90e9-9c68aa4dee4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refinement-product-type']/ul/li[2]/button/i</value>
      <webElementGuid>1929020b-1413-474d-b870-8cd626377979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/button/i</value>
      <webElementGuid>7fcee92f-d82f-471a-b8a5-409668da921c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
