<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ShopLC Dev_pushengage-opt-in-9-close</name>
   <tag></tag>
   <elementGuidId>cfad59e3-8fc0-4da1-b349-2c9a0823a913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pushengage-opt-in-9-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pushengage-opt-in-9-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#pushengage-opt-in-9-close</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a455885c-4b1e-4bac-88f9-98039e2b15fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pushengage-opt-in__sleek-opt-in-box__close-icon</value>
      <webElementGuid>2b97a2f3-d495-4c8d-a6bc-b48712d2001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pushengage-opt-in-9-close</value>
      <webElementGuid>dec8e6e8-be31-4f00-b2ef-759890be6d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pushengage-opt-in-9-close&quot;)</value>
      <webElementGuid>abe9341d-f105-446b-8ef3-220c1dc4e5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-9-close']</value>
      <webElementGuid>1b9960ae-e12b-4d38-9d15-9a991686f1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pushengage-opt-in-9']/div/div/div[2]</value>
      <webElementGuid>3a390249-c42d-4f5b-8056-0702898e00e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ShopLC Dev'])[1]/following::div[1]</value>
      <webElementGuid>b4fa05e8-a991-4184-96cc-02223979256c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notify Me'])[1]/preceding::div[5]</value>
      <webElementGuid>8c2be823-c1ed-46cb-96ed-e59ab362522a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div[2]</value>
      <webElementGuid>9f3c448d-4983-464e-9183-f99417ddc396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pushengage-opt-in-9-close']</value>
      <webElementGuid>91b5ce80-d22a-497f-95af-de81ea9a7ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
