<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_WHAT IS FAST BUY</name>
   <tag></tag>
   <elementGuidId>e0bbbe48-c51c-4b77-ae93-2dc751a329ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='activateFastBuyModal']/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#activateFastBuyModal > div.modal-dialog > div.modal-content > div.modal-header > h4.modal-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;WHAT IS FAST BUY?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>a628a126-8587-4fb1-83dd-e632ae745a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>4da0296d-b914-47b5-bad7-66a3e7fd98f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WHAT IS FAST BUY?</value>
      <webElementGuid>5781c0d4-b461-4bf6-84bd-d7f852f62b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activateFastBuyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>46f1e2d3-2619-4818-abaf-650833b55238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activateFastBuyModal']/div/div/div/h4</value>
      <webElementGuid>ed517d1c-1689-45b3-bf08-b29235e41bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[21]/following::h4[1]</value>
      <webElementGuid>c3b85572-8e1c-444a-846f-5f0c3dc27911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::h4[1]</value>
      <webElementGuid>a966ba2d-650e-4351-856c-826f0e9ff289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate Fast Buy'])[1]/preceding::h4[1]</value>
      <webElementGuid>699c5193-71f5-46b9-9d03-8c619191cfe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WHAT IS FAST BUY?']/parent::*</value>
      <webElementGuid>573ea809-4bb9-4026-af30-68139c1c852f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div/h4</value>
      <webElementGuid>dad3577c-2735-4293-b66b-bbb623b83637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'WHAT IS FAST BUY?' or . = 'WHAT IS FAST BUY?')]</value>
      <webElementGuid>2238303a-802d-4afc-9e5f-8c4b6c82a78b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
