<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select optionGoldtone ( 119.99 )Rose_df4d96</name>
   <tag></tag>
   <elementGuidId>b91d4365-2c96-4308-98ff-aa6f512ebf96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='attributeGroup-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attributeGroup-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeGroup-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c9bdf45-afcd-4bf3-82a7-6875b348228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ee3a2dc-b38d-4b0d-9b1c-9632b8680386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attributeGroupSelector</value>
      <webElementGuid>471d87a7-fec6-4e77-8141-37d2332d0865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeGroup-0</value>
      <webElementGuid>fac2e0e5-2500-4e4b-9390-8e1ffa3f4da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute-group-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f85f34a-2891-43e2-ae24-0b57f8779999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )</value>
      <webElementGuid>b18dbd1d-c9ad-4d7e-9978-c2eaa6447006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeGroup-0&quot;)</value>
      <webElementGuid>404df7f6-90fd-40da-8de0-561ea3ab1cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='attributeGroup-0']</value>
      <webElementGuid>28cad9e2-630c-40e6-a54e-97043d0df263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[4]/div/select</value>
      <webElementGuid>19e58571-b3ab-4c6a-8002-b6eaa5b5aa9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Austrian Crystal Paper Clip Chain Bracelet (7.50-9.50In) in Goldtone'])[1]/following::select[1]</value>
      <webElementGuid>cf6a794e-b4aa-47a1-998f-07cf54f06f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/preceding::select[1]</value>
      <webElementGuid>da9986b5-5f76-485a-a3d2-0ad52c831bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::select[1]</value>
      <webElementGuid>cd205cb7-c493-48a3-9c83-01990ed79da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ece09243-d5ca-4b8c-a483-8f5da7483ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'attributeGroupSelector' and @id = 'attributeGroup-0' and (text() = 'Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )' or . = 'Select optionGoldtone ( $119.99 )Rosetone ( $119.99 )Silvertone ( $119.99 )Buy All ( $359.97 )')]</value>
      <webElementGuid>d9d75a5c-82f0-418d-98e3-1b3dee1f5984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
