<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Health  Beauty</name>
   <tag></tag>
   <elementGuidId>3a5cbe12-9922-4cc5-b8e1-248aaf63070d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#health-and-beauty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='health-and-beauty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Health &amp; Beauty&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d979a7cc-7a98-46d1-a288-6128bef5ef84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/health-and-beauty</value>
      <webElementGuid>e903bb49-f6a5-41a4-b2c4-44a5b3b540d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>health-and-beauty</value>
      <webElementGuid>b8776352-d4c1-4994-ae7d-fda28f1d61bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>2d572a7c-2fa0-4f76-979b-bd9fdaaa4b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cef5c5e9-8b8b-437c-ac94-ca693f7ff8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f66c2b70-ff61-40bf-938b-027ebf6fe92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa76f287-8a3d-4465-bd85-e8e0dd652f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c4cd8fd-96c5-4403-8a83-6f6df2aa4205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>435fd2be-aea2-46c2-a875-dc64bf54f1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Health &amp; Beauty
</value>
      <webElementGuid>17f0e171-8c59-4310-9d89-62d5f7b6153b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health-and-beauty&quot;)</value>
      <webElementGuid>8fe1a2a2-520a-44f0-ad37-e17ce244dfd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='health-and-beauty']</value>
      <webElementGuid>eecaf17e-d868-43f3-9122-3186b4f6895d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-navbar-collapse']/div/div/nav/div/ul/li[11]/a</value>
      <webElementGuid>7c33adfd-bc96-4898-bf24-99e2e1aff5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Health &amp; Beauty')])[2]</value>
      <webElementGuid>a756c960-fc1d-4cb4-bfca-db3bbb061a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to previous menu'])[62]/following::a[1]</value>
      <webElementGuid>065ad7e7-ded1-4bac-a26c-2506271ddf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homesmart'])[1]/following::a[1]</value>
      <webElementGuid>4eddc8c8-535d-47a6-8c14-05253a7e774f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to previous menu'])[63]/preceding::a[1]</value>
      <webElementGuid>7088b49f-c934-447e-8359-4ffa40155200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nail Care'])[1]/preceding::a[1]</value>
      <webElementGuid>19abe8f2-9cf5-40ae-964a-e6cfd05d3476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/health-and-beauty')]</value>
      <webElementGuid>b954164d-bc2e-42ca-b6bd-d96028d391e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>ba860c72-e0ef-46e8-b2d6-34e403756564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/health-and-beauty' and @id = 'health-and-beauty' and (text() = '
Health &amp; Beauty
' or . = '
Health &amp; Beauty
')]</value>
      <webElementGuid>f0022b34-321b-4686-9559-f2a78189685f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
