<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Refine by Style fragrance_tile-image productTileImage</name>
   <tag></tag>
   <elementGuidId>830a8bc4-eb62-44a5-b094-140607a0aa5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.tile-image.productTileImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;DermaGem Ultra Restorative Anti-Aging Cream&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6b2dd45a-cece-478a-8859-fbdb253e8783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage</value>
      <webElementGuid>fc5cadd9-a47c-4b26-86b8-cd130c887c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/8/7387552/7387552_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>da7c6526-eb31-45f4-a57c-6877dc69cb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/8/7387552/7387552_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>e7bc3afd-2ed9-4188-a078-f43dd1d6ae9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/73/8/7387552/7387552.jpg?w=300&amp;h=300</value>
      <webElementGuid>a2ad7773-8df5-480b-8f1f-c07308e210d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw9b65c141/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>3f6b387f-17c8-449b-bb9f-c945ce26a947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>DermaGem Ultra Restorative Anti-Aging Cream</value>
      <webElementGuid>e9109e43-1a4c-4cca-9080-2b90e029b9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DermaGem Ultra Restorative Anti-Aging Cream</value>
      <webElementGuid>2d540112-f9fb-4b94-b449-6bdebd02dcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-9 col-xl-10&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-3 product-tile-wrapper&quot;]/div[@class=&quot;product product-listItem&quot;]/div[@class=&quot;product-tile general-tile&quot;]/div[@class=&quot;product-image-tile-body&quot;]/div[@class=&quot;image-container&quot;]/a[1]/img[@class=&quot;tile-image productTileImage&quot;]</value>
      <webElementGuid>8ba1eccc-7686-44e4-a90f-80b36d711c73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>a1fb307e-21b3-4099-9de4-e2e741fee559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='DermaGem Ultra Restorative Anti-Aging Cream']</value>
      <webElementGuid>7c1d5354-7bec-4831-a288-1618bc661db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>7cf1f218-e13e-4926-b879-acf83ae67301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image.shoplc.com/products/73/8/7387552/7387552_1.jpg?w=300&amp;h=300' and @alt = 'DermaGem Ultra Restorative Anti-Aging Cream' and @title = 'DermaGem Ultra Restorative Anti-Aging Cream']</value>
      <webElementGuid>525538d9-d8ea-4c9c-975d-2e1c85087f84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
