<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADD TO CART</name>
   <tag></tag>
   <elementGuidId>1583c1cc-21e4-4d40-88b2-623d8dfd4e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='liveTvShopLast24Grid']/div/div/div[2]/div[3]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.add-to-cart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;ADD TO CART&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cf6a360-1f4b-469e-bf3a-68030b7e0a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-to-cart</value>
      <webElementGuid>97c5ea15-55a0-4c09-9620-c38dbf1b0296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADD TO CART</value>
      <webElementGuid>36e9d84b-d0bb-4612-ae19-4a90b937563d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;liveTvShopLast24Grid&quot;)/div[@class=&quot;product-grid shop-last-grid d-flex flex-wrap&quot;]/div[@class=&quot;product-tile-wrapper shop-last-tile  product&quot;]/div[@class=&quot;product-tile d-flex&quot;]/div[@class=&quot;actions flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;d-flex actions-row actions-wrapper m-0 shop-items&quot;]/div[@class=&quot;text-center cart-wrapper fast-buy-present&quot;]/a[@class=&quot;add-to-cart&quot;]</value>
      <webElementGuid>fc9cd1f6-0229-4b27-901d-904ce45a2661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvShopLast24Grid']/div/div/div[2]/div[3]/div[2]/div/a</value>
      <webElementGuid>7e1cc863-7943-488e-9e27-9524c0d785f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD TO CART')]</value>
      <webElementGuid>8ea1cc17-a679-40c5-b133-545336d913f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUICK VIEW'])[1]/following::a[1]</value>
      <webElementGuid>aea4a62f-452b-43f1-937d-71afcb13603d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sold'])[1]/following::a[3]</value>
      <webElementGuid>6fd0c924-cbce-4bfb-bf77-537be98b9498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAST BUY'])[2]/preceding::a[1]</value>
      <webElementGuid>14935f15-1ad8-4989-af5c-334e6b51005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD TO CART']/parent::*</value>
      <webElementGuid>a64907c2-4e60-4a4a-b2b0-edc2fdf33bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/a</value>
      <webElementGuid>776fb33d-c8d6-425a-8468-d26cb5f79dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'ADD TO CART' or . = 'ADD TO CART')]</value>
      <webElementGuid>b4772101-a605-407a-a5c8-425fd8fbfbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
