<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_WHAT IS FAST BUY</name>
   <tag></tag>
   <elementGuidId>bb6b8803-aca6-4d5c-bca5-1919f7e4aecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#activateFastBuyModal > div.modal-dialog > div.modal-content > div.modal-header > h4.modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='activateFastBuyModal']/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;WHAT IS FAST BUY?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ae88c77c-98dd-4632-9901-f47a19a676be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>3b48d9b3-9c52-45c3-893d-e307a4b06694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WHAT IS FAST BUY?</value>
      <webElementGuid>7113464b-bd5b-4769-bd1d-7d365d4b0748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activateFastBuyModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>2fe6e11a-0ddf-45f0-b9f2-d5fe10e04910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='activateFastBuyModal']/div/div/div/h4</value>
      <webElementGuid>08f5119d-25e2-4a88-8c6d-0eb16adcbd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notify Me'])[1]/following::h4[1]</value>
      <webElementGuid>1698d422-0c23-4246-a937-b50053b552ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate Fast Buy'])[1]/preceding::h4[1]</value>
      <webElementGuid>7791c5db-9b85-44e7-a5cf-f6c287052692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WHAT IS FAST BUY?']/parent::*</value>
      <webElementGuid>f97285fc-d01d-4cc1-9b22-4f89cbe2bd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/h4</value>
      <webElementGuid>d9077abb-52ff-4767-a0a5-c9793e788960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'WHAT IS FAST BUY?' or . = 'WHAT IS FAST BUY?')]</value>
      <webElementGuid>e12d34de-46f1-4a3f-8331-d5fdecd0e0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
