<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact_dwfrm_billing_contactInfoFields_email</name>
   <tag></tag>
   <elementGuidId>0d924b92-5fa3-49bc-8368-8885567da697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkoutGuestEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkoutGuestEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>974d5826-fac5-4cf1-b059-bdc5bfa34998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e566ceb-177f-450f-a6a8-d7ff2de44f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>214e0e0e-70a2-48f3-9511-12c9fac8bbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom prefilled email</value>
      <webElementGuid>82d3f87f-7290-4732-a2ba-c5bb84af8a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkoutGuestEmail</value>
      <webElementGuid>33e65e43-91a7-41b7-bfb0-d19e6f3ddcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-empty-email</name>
      <type>Main</type>
      <value>Please enter your email address before proceeding further</value>
      <webElementGuid>af6873bc-72fc-4d12-8650-9dc67055a4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-email-invalid</name>
      <type>Main</type>
      <value>Please enter a valid email address.</value>
      <webElementGuid>1178fbc1-882f-443b-829a-cff796c91a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_billing_contactInfoFields_email</value>
      <webElementGuid>cb48d0a4-91eb-4fbc-9a02-bba0099ee91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>45e6340e-e8a8-4559-9ab7-522d5361ea95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\w.%+\-]+@[\w.\-]+\.[\w]{2,6}$</value>
      <webElementGuid>0569c872-17ef-4c44-9e18-311284dd2277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>emailInvalidMessage</value>
      <webElementGuid>a205863e-ab8b-4fd8-b143-23c5eb13c2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutGuestEmail&quot;)</value>
      <webElementGuid>449e8e10-242b-4112-a6d8-af849442bd49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkoutGuestEmail']</value>
      <webElementGuid>a20aa361-41b8-4a93-8b59-3b667afd26ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-main']/div/div/div[9]/form/div/div/div/input</value>
      <webElementGuid>3387d3ba-de56-4a1a-b9b3-541ca2f9d85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/form/div/div/div/input</value>
      <webElementGuid>5e6cf683-e323-4bf5-bbf5-efb618e8f10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Email' and @id = 'checkoutGuestEmail' and @name = 'dwfrm_billing_contactInfoFields_email']</value>
      <webElementGuid>fa5a07d6-4638-4ff0-9133-6e98f1b1d5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
