<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hair Care</name>
   <tag></tag>
   <elementGuidId>d35589e7-7b21-4ecd-9b5c-ebfa7da04eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#haircare</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='haircare']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Hair Care&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2b408a7-596b-49bd-b7eb-7cab2d31b089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/haircare</value>
      <webElementGuid>d7fd17a4-83d1-4a98-923f-d088acd5067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>haircare</value>
      <webElementGuid>780fbfb9-92f7-4bce-8eab-0cee1738b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-link </value>
      <webElementGuid>7e957bcb-9c60-414c-807e-cdc10882aafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>906904e6-c52b-4cdb-acd6-8e62afa80e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50e9abed-bc17-4af5-8b9a-9720d73fdfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hair Care</value>
      <webElementGuid>feaaa450-9a02-420e-9f88-5712660d7e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;haircare&quot;)</value>
      <webElementGuid>7d5928e1-57f4-41f6-bddb-4da3d0eebf4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='haircare']</value>
      <webElementGuid>f1c61a33-7fdb-4bd0-a219-671896bd97b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-navbar-collapse']/div/div/nav/div[2]/ul/li[11]/ul/li/ul/li[2]/a</value>
      <webElementGuid>a656f41f-39f9-481a-bb70-e568f2bb32aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hair Care')]</value>
      <webElementGuid>d29e5466-1192-4b41-b65e-087e070ccfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nail Care'])[1]/following::a[1]</value>
      <webElementGuid>0f934701-720b-46f7-b73c-da14f51da2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health &amp; Beauty'])[2]/following::a[2]</value>
      <webElementGuid>0f8b521b-2f55-4ce5-aa81-8641a76913af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wigs &amp; Hair Accessories'])[1]/preceding::a[1]</value>
      <webElementGuid>34d27c9c-e54e-4885-923e-09877e7f1816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools and Accessories'])[1]/preceding::a[2]</value>
      <webElementGuid>46730ecf-4ce4-4d3d-9fbb-7860ed54f8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hair Care']/parent::*</value>
      <webElementGuid>c0e1586e-ea5a-4ca4-a8c8-3b978040467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/haircare')]</value>
      <webElementGuid>e05f145a-b3a1-453a-9c78-73ccaa97ef85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/ul/li/ul/li[2]/a</value>
      <webElementGuid>f3ea8320-7ddf-42ad-a942-453a6d6e5179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/haircare' and @id = 'haircare' and (text() = 'Hair Care' or . = 'Hair Care')]</value>
      <webElementGuid>f1e6ede0-ace3-42cd-96ce-f719f3f68b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
