<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Remove filter Currently Refined by Prod_19686a</name>
   <tag></tag>
   <elementGuidId>31892750-caa8-4f63-bf61-b1b5eb7d1b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wishlist-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div/div[2]/button/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wishlist-air-container > button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9da73f2-962d-47e6-ba7c-d50e14fb82d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlist-icon</value>
      <webElementGuid>5a35b2e1-8860-45d0-8659-7947a4af96cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw67a45457/images/Normal-Wishlist.svg</value>
      <webElementGuid>c814e416-ade7-45d3-a458-3db88edbaf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d9fd499d-b3b9-4388-afff-f0552f3d64fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-9 col-xl-10&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-3 product-tile-wrapper&quot;]/div[@class=&quot;product product-listItem&quot;]/div[@class=&quot;product-tile general-tile&quot;]/div[@class=&quot;producttag-automation-image&quot;]/div[@class=&quot;wishlist-air-container&quot;]/button[@class=&quot;btn wishlistTile custom-add-wishlist-btn wl-toggle&quot;]/span[@class=&quot;wishlist-icon&quot;]/img[@class=&quot;wishlist-icon&quot;]</value>
      <webElementGuid>922b14ed-bde2-420c-adbb-4c291d377623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div/div[2]/button/span/img</value>
      <webElementGuid>af4c6ba9-4e45-47c7-8fbb-391a366590f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Login'])[3]</value>
      <webElementGuid>2ef031f5-2e46-45da-9c36-2492d2970f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>5b281af0-df54-4797-a1e9-3668e762c1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw67a45457/images/Normal-Wishlist.svg' and @alt = 'Login']</value>
      <webElementGuid>7acb2783-8bc6-4660-8769-352c5802a3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
