<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Style_tile-image productTileImage</name>
   <tag></tag>
   <elementGuidId>3759f79d-fa6a-488e-a9f7-2488223b44b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.tile-image.productTileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ee428d1-92c7-4a26-a2db-90c49a8e952c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage</value>
      <webElementGuid>a165809d-0094-4686-a8a8-b79571bc91c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/41/4/4147324/4147324_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>13989e71-5190-4555-8b8e-546422fa6f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/41/4/4147324/4147324_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>890f2eee-18c8-4fb3-a304-b31500e58559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/41/4/4147324/4147324.jpg?w=300&amp;h=300</value>
      <webElementGuid>1113b602-90fe-4359-a4a6-849d5b530db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dwcd84a74d/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>c478272c-e142-4bda-90a9-0564421a9e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil</value>
      <webElementGuid>fc5ab6b4-263f-4c6c-a8dd-4eb376b9a25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil</value>
      <webElementGuid>b753a73b-21e6-4515-8eaf-7ac0590ffcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-9 col-xl-10&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-3 product-tile-wrapper&quot;]/div[@class=&quot;product product-listItem&quot;]/div[@class=&quot;product-tile general-tile&quot;]/div[@class=&quot;product-image-tile-body&quot;]/div[@class=&quot;image-container&quot;]/a[1]/img[@class=&quot;tile-image productTileImage&quot;]</value>
      <webElementGuid>43951341-1ac0-4565-9a3b-bf872039ed3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>6eb9c851-dc97-4d18-bae2-9f80d1222f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil']</value>
      <webElementGuid>12ce7616-2b77-4f9d-98b4-56fc0bf9e4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>cd691455-0342-41ef-af5d-6e7b548ff27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image.shoplc.com/products/41/4/4147324/4147324_1.jpg?w=300&amp;h=300' and @alt = 'Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil' and @title = 'Marigold &amp; Lotus Cold Pressed Natural Jojoba Oil 7 oz with Free Travel Size Cold Pressed Jojoba Oil']</value>
      <webElementGuid>109e188a-5bdf-455a-9224-d1da14acf551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
