<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy Now</name>
   <tag></tag>
   <elementGuidId>5d690187-35b9-4fbd-88e5-0cc46c943cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToCheckout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='continueToCheckout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#continueToCheckout</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed5f2709-76da-44da-9bec-3572b7b57115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToCheckout</value>
      <webElementGuid>6a02f464-a294-4959-83cf-733594e10be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>livetv-add-to-cart</value>
      <webElementGuid>98f0cc22-835d-446b-9c8a-203ccdea5158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>/on/demandware.store/Sites-SHOP_LC-Site/en_US/Checkout-Login?cartType=normalproducts&amp;isLivetvCheckout=true</value>
      <webElementGuid>b64949bd-7775-4736-9bb4-96f965965a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>139.99</value>
      <webElementGuid>9b919384-24a8-4cc5-9c8c-1068ce56df2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brand</name>
      <type>Main</type>
      <value>Shop LC</value>
      <webElementGuid>62fe12a9-8c6c-4f8b-82dc-d2008bdd4305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>Live</value>
      <webElementGuid>06b3083c-21a4-4fc5-98bb-a7e52cd86737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Buy Now
            </value>
      <webElementGuid>e94449dc-03f4-4f95-9690-02185c6cc687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToCheckout&quot;)</value>
      <webElementGuid>af5ffaf3-40cc-4fa6-af64-a6efc330f4ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='continueToCheckout']</value>
      <webElementGuid>9641dfa6-cbd3-4f9d-89d9-69be9732508d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[5]/a</value>
      <webElementGuid>cc1cde20-1179-4d86-bacd-ea048e3d25c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/following::a[1]</value>
      <webElementGuid>fe98b22e-86f6-45e3-8248-32e2024fc6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(interest free)'])[1]/following::a[1]</value>
      <webElementGuid>0b658c5e-ab15-46a4-9a25-73f61eeec33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAST BUY'])[1]/preceding::a[1]</value>
      <webElementGuid>d1ebc872-4f47-4459-b42c-3a07211ba796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>34551a70-dd25-49e9-b684-20f840aaad86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'continueToCheckout' and (text() = '
                Buy Now
            ' or . = '
                Buy Now
            ')]</value>
      <webElementGuid>b769a2a1-eb70-416e-9254-eab816986a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
