<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select optionSIZE 0 ( 138.99 )Apple _98bd9c</name>
   <tag></tag>
   <elementGuidId>5423cfc2-2a08-4afd-8e6d-fdc6c229ff8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attributeGroup-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='attributeGroup-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeGroup-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b847b30-3b1c-4a35-8d98-ed64d24cdd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70bf54f5-2be7-4daa-afa7-93f1f9b3ff03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attributeGroupSelector</value>
      <webElementGuid>f59ca6ee-2508-4d62-ba76-fdb3a6150acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeGroup-0</value>
      <webElementGuid>1eee5536-c553-453a-aad2-fb861ae58d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute-group-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9387bcd8-25b6-4f09-ab3d-e1090b63c805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select optionSIZE 0 ( $138.99 )Apple Cinnamon ( $138.99 )Amethyst ( $138.99 )Amethyst-1 ( $138.99 )Buy All ( $500.36 )</value>
      <webElementGuid>6ce60ccd-3793-4196-b76a-197701ee7281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeGroup-0&quot;)</value>
      <webElementGuid>40a508cb-5ddd-413c-bdf6-d7e0120b9b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='attributeGroup-0']</value>
      <webElementGuid>991b7d64-9e1b-4985-9e17-b244fcd94e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[4]/div/select</value>
      <webElementGuid>f8db23c4-e21d-4546-817c-6c2fab82b3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(interest free)'])[1]/following::select[1]</value>
      <webElementGuid>d981c6e0-271a-4e60-b65b-d41ba2af60ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/preceding::select[1]</value>
      <webElementGuid>261a99a2-ee94-42a3-a57e-c1c85954ed18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::select[1]</value>
      <webElementGuid>9a4783dd-370e-4329-9457-42140201cc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>70421bc7-3734-4a21-9830-1ec825a4a36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'attributeGroupSelector' and @id = 'attributeGroup-0' and (text() = 'Select optionSIZE 0 ( $138.99 )Apple Cinnamon ( $138.99 )Amethyst ( $138.99 )Amethyst-1 ( $138.99 )Buy All ( $500.36 )' or . = 'Select optionSIZE 0 ( $138.99 )Apple Cinnamon ( $138.99 )Amethyst ( $138.99 )Amethyst-1 ( $138.99 )Buy All ( $500.36 )')]</value>
      <webElementGuid>46eed487-6148-4236-b3bb-e9b10ff1912a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
