<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Refine by Style fragrance_tile-image productTileImage</name>
   <tag></tag>
   <elementGuidId>aaf1d80f-2cae-4484-b58b-a2a8ac442bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.tile-image.productTileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb9ce7c1-f5c2-4659-b2b4-55a00f5d632e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-image productTileImage</value>
      <webElementGuid>07fa57a6-6f34-4c8b-813c-4e7914b8c081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>d9792cbd-a513-43b4-8024-05c4a915edc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-secondary-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300</value>
      <webElementGuid>bc67d470-aa29-4dcc-837a-ddb02fdd2c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/products/34/9/3494681/3494681.jpg?w=300&amp;h=300</value>
      <webElementGuid>ff4f74b4-01ed-462c-93b1-8397848e3f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw475e4155/images/img_no_thumbnail.jpg';</value>
      <webElementGuid>156534c6-a1eb-407b-aae6-9e2aa618f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)</value>
      <webElementGuid>867c7106-39f1-4e33-b050-96891e2037f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)</value>
      <webElementGuid>38fd9d23-e226-4a45-a772-83085bb123cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search-results&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-9 col-xl-10&quot;]/div[@class=&quot;row product-grid&quot;]/div[@class=&quot;col-6 col-lg-4 col-xl-3 product-tile-wrapper&quot;]/div[@class=&quot;product product-listItem&quot;]/div[@class=&quot;product-tile general-tile&quot;]/div[@class=&quot;product-image-tile-body&quot;]/div[@class=&quot;image-container&quot;]/a[1]/img[@class=&quot;tile-image productTileImage&quot;]</value>
      <webElementGuid>6b5bc91a-35e1-4976-a2c6-e54c52b6de32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search-results']/div[2]/div[2]/div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>39e5a7e1-a983-401d-8990-a0a4ef0f70f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)']</value>
      <webElementGuid>8d6c3a52-4a48-43d4-b16d-50fb95c57ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/a/img</value>
      <webElementGuid>c76be567-d26c-490a-9680-915465d5acb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://image.shoplc.com/products/34/9/3494681/3494681_1.jpg?w=300&amp;h=300' and @alt = 'The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)' and @title = 'The Jojoba Company Natural Certified Organic Jojoba Oil For Face, Hair and Body| Anti Aging Oil (200 ML)']</value>
      <webElementGuid>09fba2ee-4487-43fa-b573-af690c8e1d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
