<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Wishlist_header-menu-icon</name>
   <tag></tag>
   <elementGuidId>c02763f4-cf62-4f11-8b8d-0ed3a8840ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.minicart-link.d-flex.align-items-center > img.header-menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Cart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cart 1 Items&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>272c24e4-43f6-45da-a3c1-74bdc01c31a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-menu-icon</value>
      <webElementGuid>30b5a0cc-45d9-4e86-89af-a61eb6d6753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw590c13b3/images/black/Cart-icon.svg</value>
      <webElementGuid>b093adbf-2d48-4dbc-9a7e-ec7e854f48da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>79f780d1-21f8-4a7d-b009-f67990d233a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f30cb33e-134a-427f-a060-cbcb8a4e7ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ce11dcb4-6979-4a16-9346-a77795a23db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sticky-top&quot;]/div[@class=&quot;page&quot;]/header[1]/nav[@class=&quot;nav-header&quot;]/div[@class=&quot;fixed-top stickyHeader&quot;]/div[@class=&quot;container-orignal-LS container header spacing-sm&quot;]/div[@class=&quot;row align-items-center header-nav&quot;]/div[@class=&quot;col-lg-5 col-md-6 col-7 pl-md-4 pr-xs-0&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;minicart text-center&quot;]/div[@class=&quot;minicart-total hide-link-med&quot;]/a[@class=&quot;minicart-link d-flex align-items-center&quot;]/img[@class=&quot;header-menu-icon&quot;]</value>
      <webElementGuid>24f05528-923d-4f57-91ff-7f7084588978</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cart']</value>
      <webElementGuid>2f5155a0-2611-4ef9-a9fd-af8e4d4f282c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/img</value>
      <webElementGuid>e9d6fb11-a759-4cf8-93d0-d6b3622ccc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/on/demandware.static/Sites-SHOP_LC-Site/-/default/dw590c13b3/images/black/Cart-icon.svg' and @alt = 'Cart']</value>
      <webElementGuid>296eec4d-18a2-4b8b-a685-b083e4399f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
