<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy Now</name>
   <tag></tag>
   <elementGuidId>abf800b3-f8c8-45c5-965c-e2f251989d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continueToCheckout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='continueToCheckout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#continueToCheckout</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>940b63b9-7c9f-436b-90e3-22d39df031f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continueToCheckout</value>
      <webElementGuid>e732d818-b132-4b06-bc1d-8072969c6466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>livetv-add-to-cart</value>
      <webElementGuid>b83e098c-164e-4adb-8f04-d85cb5c2d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>/on/demandware.store/Sites-SHOP_LC-Site/en_US/Checkout-Login?cartType=normalproducts&amp;isLivetvCheckout=true</value>
      <webElementGuid>11216345-b2d6-4d21-bc55-6b944c8443b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>79.99</value>
      <webElementGuid>f15794f5-9808-486c-b96e-7ce8810b524e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-brand</name>
      <type>Main</type>
      <value>Shop LC</value>
      <webElementGuid>b075d3da-905b-4208-917f-6253a825eb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-category</name>
      <type>Main</type>
      <value>4th</value>
      <webElementGuid>d18bf340-f25d-44b3-84b3-dcd00fb01cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Buy Now
            </value>
      <webElementGuid>267af35a-7c38-4255-ab50-dacb36248ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueToCheckout&quot;)</value>
      <webElementGuid>024874ec-3447-4db6-817e-82aad1dd878c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='continueToCheckout']</value>
      <webElementGuid>8ebb3d95-d16f-40f5-b158-0097c41abbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[5]/a</value>
      <webElementGuid>a9bd9366-4daf-42ca-862c-d1f2c48687fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/following::a[1]</value>
      <webElementGuid>9366411d-3d64-4751-b38e-7db935c641c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAST BUY'])[1]/preceding::a[1]</value>
      <webElementGuid>78262883-c731-4071-80d6-c56d3fd1537b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>7f9978a1-d243-43fd-8188-04c351f7f1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'continueToCheckout' and (text() = '
                Buy Now
            ' or . = '
                Buy Now
            ')]</value>
      <webElementGuid>c20aee52-c3f9-4352-ae3b-496dd2f19269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
