<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select optionBlack ( 78.99 )Butterfl_4d3db6</name>
   <tag></tag>
   <elementGuidId>8c029253-5f2d-4809-91e1-8ad5567edcf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attributeGroup-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='attributeGroup-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeGroup-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>443e4bd6-dffe-4258-a4ed-a8c048477621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5da975a6-b00a-45a7-acaf-9aa73696d2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attributeGroupSelector</value>
      <webElementGuid>5ee3025d-fa11-4d76-9ebf-035c47dbb52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeGroup-0</value>
      <webElementGuid>b7a5edb9-f97a-49db-9c86-6a5d75a4878f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute-group-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e151d0fc-8846-47e3-88b5-70e65f358707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select optionBlack ( $78.99 )Butterfly ( $78.99 )Blue ( $78.99 )Golden ( $78.99 )Teal Blue ( $78.99 )Red ( $78.99 )Heart ( $78.99 )Buy All ( $552.93 )</value>
      <webElementGuid>a56bff4e-7141-4ec6-b814-449ccfe1dade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeGroup-0&quot;)</value>
      <webElementGuid>f06069be-dc2c-4637-bb27-4ffd07bc2d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='attributeGroup-0']</value>
      <webElementGuid>8cbab6f3-7c72-467c-bcdd-3add185b20cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[4]/div/select</value>
      <webElementGuid>adecf5c1-8ca9-4b6d-936c-dbb00f22bcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Murano Style on Blue Sandstone Beaded Necklace 18-20 Inches in Stainless Steel 183.00 ctw'])[1]/following::select[1]</value>
      <webElementGuid>1ab0fa7a-4ce3-40d9-8ed1-a5f0c7c498d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/preceding::select[1]</value>
      <webElementGuid>347767e8-d45a-416e-a9db-f91f624753bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::select[1]</value>
      <webElementGuid>bdc86be3-3191-4bf4-81cd-e024c35e8595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>bf55a9e8-4861-488c-8034-7d763db2386c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'attributeGroupSelector' and @id = 'attributeGroup-0' and (text() = 'Select optionBlack ( $78.99 )Butterfly ( $78.99 )Blue ( $78.99 )Golden ( $78.99 )Teal Blue ( $78.99 )Red ( $78.99 )Heart ( $78.99 )Buy All ( $552.93 )' or . = 'Select optionBlack ( $78.99 )Butterfly ( $78.99 )Blue ( $78.99 )Golden ( $78.99 )Teal Blue ( $78.99 )Red ( $78.99 )Heart ( $78.99 )Buy All ( $552.93 )')]</value>
      <webElementGuid>eff68be4-1347-44af-bb57-09dcbcb2f895</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
