<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hair Care</name>
   <tag></tag>
   <elementGuidId>0035bbeb-55d4-48bd-81fa-f192f27f63c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#haircare</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='haircare']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Hair Care&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3270c5d-b7fb-4d2e-96ff-d43de516d19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/c/haircare</value>
      <webElementGuid>b90814ee-094a-4b8a-a8c8-008481128df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>haircare</value>
      <webElementGuid>668ce940-4add-43a0-82ca-54b1b78a28eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-link </value>
      <webElementGuid>6bb13207-0cc3-4818-af68-1e5dee0e8f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fbf28ad-8b8f-4588-bf8e-27012f77030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e78ea7f-19dc-4133-95ba-dfa5c3d65511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hair Care</value>
      <webElementGuid>59e75e7f-5f22-4339-bb21-e1d3ce45c84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;haircare&quot;)</value>
      <webElementGuid>d517c03f-1e16-4f10-9639-ac3a107cc4bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='haircare']</value>
      <webElementGuid>32b0f435-9398-4a27-a6d2-733c12ca6efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sg-navbar-collapse']/div/div/nav/div[2]/ul/li[11]/ul/li/ul/li[2]/a</value>
      <webElementGuid>db798a5f-8326-43dd-ae5b-144aeb31796f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hair Care')]</value>
      <webElementGuid>bffa1a15-2b95-4c36-bc20-8bc7e8a750ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nail Care'])[1]/following::a[1]</value>
      <webElementGuid>19e2f0a6-5ec4-4def-a585-63fe09a42a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health &amp; Beauty'])[2]/following::a[2]</value>
      <webElementGuid>236a7acb-6d6c-4414-9b9a-8b86cd9c0fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wigs &amp; Hair Accessories'])[1]/preceding::a[1]</value>
      <webElementGuid>8f40b10d-ae39-4ec2-a63f-3ff6c692722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools and Accessories'])[1]/preceding::a[2]</value>
      <webElementGuid>a2905004-2839-4b55-a350-a871ad254131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hair Care']/parent::*</value>
      <webElementGuid>af4f3791-b5cb-427d-849b-3c8fffc148ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/c/haircare')]</value>
      <webElementGuid>b9c90912-eeb9-4e53-ab62-d8892dbc59c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/ul/li/ul/li[2]/a</value>
      <webElementGuid>4a36be7e-d311-4551-aec6-6e5b279d6013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/c/haircare' and @id = 'haircare' and (text() = 'Hair Care' or . = 'Hair Care')]</value>
      <webElementGuid>d6d4f1ef-9919-4951-98e9-db6921894063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
