<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select optionBlack ( 79.99 )Butterfl_7e6718</name>
   <tag></tag>
   <elementGuidId>c4b4b57a-05c3-46bf-b1b6-44af7fd06e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attributeGroup-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='attributeGroup-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#attributeGroup-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7813400-de54-4529-bd2e-91a6fe1abbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc4f8bd5-709c-4a07-9814-08b9ec8448e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attributeGroupSelector</value>
      <webElementGuid>73cae5b0-0e02-4235-b52b-53c039110e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attributeGroup-0</value>
      <webElementGuid>30d92851-e58b-4652-adcc-4fe210dbcc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute-group-order</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b56532b5-73d5-4438-bc91-76e6a5d58390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select optionBlack ( $79.99 )Butterfly ( $99.99 )Blue ( $59.99 )Golden ( $79.99 )Teal Blue ( $59.99 )Red ( $79.99 )Heart ( $79.99 )Buy All ( $539.93 )</value>
      <webElementGuid>1abc12a7-5483-4ce9-bac7-9ffeb6ab3415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attributeGroup-0&quot;)</value>
      <webElementGuid>8f8c8ec8-0cbb-44db-af0a-956498cd8786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='attributeGroup-0']</value>
      <webElementGuid>968158c9-8628-4f94-b391-ab05be12dac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='liveTvPDPSection']/div/div[2]/div[4]/div/select</value>
      <webElementGuid>a0660527-eb09-47e1-a3dc-a0d8a7008915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Murano Style on Blue Sandstone Beaded Necklace 18-20 Inches in Stainless Steel 183.00 ctw'])[1]/following::select[1]</value>
      <webElementGuid>56666216-0d67-4098-955f-a45d07f8114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty :'])[1]/preceding::select[1]</value>
      <webElementGuid>f326b9dc-1e8a-49e6-9888-b65d2c288062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::select[1]</value>
      <webElementGuid>96af65fe-9fd7-4667-9829-14e1e8ced82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a8aa0786-0a35-4463-b01f-a319bd9a965c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'attributeGroupSelector' and @id = 'attributeGroup-0' and (text() = 'Select optionBlack ( $79.99 )Butterfly ( $99.99 )Blue ( $59.99 )Golden ( $79.99 )Teal Blue ( $59.99 )Red ( $79.99 )Heart ( $79.99 )Buy All ( $539.93 )' or . = 'Select optionBlack ( $79.99 )Butterfly ( $99.99 )Blue ( $59.99 )Golden ( $79.99 )Teal Blue ( $59.99 )Red ( $79.99 )Heart ( $79.99 )Buy All ( $539.93 )')]</value>
      <webElementGuid>059708f9-2f3e-4633-92f4-65113d767efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
