<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or Phone Number_loginEmail</name>
   <tag></tag>
   <elementGuidId>223eb982-a4da-4320-90a5-8b2803ffad56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-form-email-phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-form-email-phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email or Phone Number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6feadcd-40b2-45cc-a119-973a646ed7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9814af2c-aa5f-4f81-9f53-56ca8d62d5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-form-email-phone</value>
      <webElementGuid>01d2e801-8c63-4941-a314-29168475e674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c22040d3-b6f9-40e8-b97a-d62105e1ebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>1814cd38-39cb-447e-afce-f3a266e9c68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Please enter Email or Phone Number</value>
      <webElementGuid>3241e2a2-adfe-42cd-960b-3a9435cd0541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>form-email-error</value>
      <webElementGuid>f0dd9c8b-788e-442a-b2f8-3e3a8f598daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginEmail</value>
      <webElementGuid>f91e18c7-47f4-4747-947d-3b8489eb5842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-email-phone&quot;)</value>
      <webElementGuid>1419f175-ea40-4652-bec3-cd154386bda9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-form-email-phone']</value>
      <webElementGuid>1511a051-3471-4e50-a61a-b2e50ee5e412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/input</value>
      <webElementGuid>69ccbe1c-ff7a-4a25-bd85-c5c03a1a843a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>7fa4ab26-f2bf-4094-9518-2f839a0685ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'login-form-email-phone' and @name = 'loginEmail']</value>
      <webElementGuid>c1461e8c-0f99-444e-b319-90c59e9b39a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
