<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>21a1dc78-0a7b-46b2-afe8-bcacae540284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='SHOPLC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;SHOPLC&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;SHOPLC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f8e4332c-a18d-4e53-88aa-b8d3726dfee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev01.shoplc.com/on/demandware.static/-/Sites-SHOP_LC-Library/default/dw84bd68e1/images/ShopLC-Logo.svg</value>
      <webElementGuid>566df33c-1206-45f6-ba61-2e3823b8797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SHOPLC</value>
      <webElementGuid>2683147f-6304-4f60-b599-cf6bf69e151d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>025c0f7f-9ba9-403b-94b8-310a604620b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>b43ee211-cffb-4e45-b03e-1755756c2489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page&quot;]/header[1]/nav[@class=&quot;border-cart-header&quot;]/div[@class=&quot;header cart-header container-orignal-LS container spacing-sm&quot;]/div[@class=&quot;row align-items-center cart-header-align&quot;]/div[@class=&quot;col-3 col-md-2 col-lg-1&quot;]/div[@class=&quot;brand-logo&quot;]/a[@class=&quot;logo-home&quot;]/div[@class=&quot;content-asset&quot;]/img[1]</value>
      <webElementGuid>9924d8ff-0e1f-4de3-98a3-abe647dcc009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SHOPLC']</value>
      <webElementGuid>d0ea27b6-d535-4bb9-927f-033a02db5aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5c8411ea-a818-49ae-b676-938edfe8992d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev01.shoplc.com/on/demandware.static/-/Sites-SHOP_LC-Library/default/dw84bd68e1/images/ShopLC-Logo.svg' and @alt = 'SHOPLC']</value>
      <webElementGuid>f45e04a0-89d9-47ec-b346-e479cf86fa0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
