<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue to Review Order</name>
   <tag></tag>
   <elementGuidId>d30408ff-bdb5-4bdb-ab5d-335ee9c9d48c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;submit-button-initial&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54155d5a-d076-42fc-8519-4b0d9e170cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ead3f0aa-ea56-4d01-b847-3eaf459d08ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Buttons_base_2xi07 CheckoutButton_noMargin_mv-3h xo-member-c72rwi-button_base-text_button_lg-btn_full_width</value>
      <webElementGuid>9ffa5665-045b-4395-a4c3-6ff065b3c606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ppui-info</name>
      <type>Main</type>
      <value>buttons_7.10.4__7.42.2</value>
      <webElementGuid>d7f0b586-e1d6-4b38-80fa-cb949800a3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-submit-btn</value>
      <webElementGuid>768b0ebd-3dc2-48ed-ada1-3f4e9b2cec79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-button-initial</value>
      <webElementGuid>0235aeff-8e91-4156-b28e-4cd392e34934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa57ae1c-81cb-46c2-9c29-6894a024b478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to Review Order</value>
      <webElementGuid>b5b35fd5-c8a0-42f9-bc62-8cd0f9854dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-submit-btn&quot;)</value>
      <webElementGuid>67d3b0ba-1a56-441d-a474-f8387e2db217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-submit-btn']</value>
      <webElementGuid>28b9bf31-af0d-4d56-9d08-51cdcda1931d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hermione-container']/div/main/div[3]/div[2]/button</value>
      <webElementGuid>6fb96cbf-8ea9-4505-b7de-ddd9b632a2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[2]/following::button[1]</value>
      <webElementGuid>9b2983e9-c3b8-4bd1-b556-7dcbb6459c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment method rights'])[1]/preceding::button[1]</value>
      <webElementGuid>0c74af1b-ef25-4f03-a04c-ccd012f8c888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue to Review Order']/parent::*</value>
      <webElementGuid>02fb8db2-beba-4b32-89f6-5dc408f97db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>74941545-bad3-4bdf-9854-4c0e205e05e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-submit-btn' and (text() = 'Continue to Review Order' or . = 'Continue to Review Order')]</value>
      <webElementGuid>87066d2f-e665-4d47-a3b8-3047126b50eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
