<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Our Can, , t-Miss List)_img-flui_359b27</name>
   <tag></tag>
   <elementGuidId>c2e20e74-fc59-40f5-b65d-af4f9a19b898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homepage-SHOP_LC']/div/div/div/div[6]/div/div/div/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.categoryWrapper > img.img-fluid.ITC-image.common-image-component.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;$1 Auctions Cat1 $1 Auctions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7b54172-687b-4bfe-a45d-af0a89cdd3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>$1 Auctions Cat1</value>
      <webElementGuid>afe0da33-e81b-4b26-ad1a-a065d3c99fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid ITC-image common-image-component lazyloaded</value>
      <webElementGuid>3943c5a1-1632-4245-92bf-4b6d19d27217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/Banners/June2024/08.06/C1.jpg</value>
      <webElementGuid>ec169e32-29cc-4e43-a0c3-20193a0d7c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>$1 Auctions </value>
      <webElementGuid>13513896-b12b-4f4d-a4d4-df1daee90b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>896be614-0276-44ca-9f45-86156d868179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>bdcff236-ff4a-4cb6-ba20-d66246e9dcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promotionslot</name>
      <type>Main</type>
      <value>6-cat-hp-section</value>
      <webElementGuid>3cb78d34-dece-4e81-bff3-f3e3c2ef8f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.shoplc.com/Banners/June2024/08.06/C1.jpg</value>
      <webElementGuid>2ad09d33-a3cb-450f-ac25-5a0ded5da348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-first-on-screen881697_638</name>
      <type>Main</type>
      <value>13459</value>
      <webElementGuid>04c653bc-a986-4f59-89da-a67efd160272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-total-visible-time881697_638</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0a69a5f7-5b03-4e3e-ab92-24fbe954d9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-vis-has-fired881697_638</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>05f77d87-9bf9-41e3-9165-a3905bf7e9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homepage-SHOP_LC&quot;)/div[@class=&quot;container container-orignal-LS&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_assets-includeContentAsset&quot;]/div[@class=&quot;content-asset&quot;]/div[@class=&quot;mainLPWrapper mobile-2r-1c&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;CateogryBannerWrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4 col-sm-2 fade3&quot;]/a[@class=&quot;categoryWrapper&quot;]/img[@class=&quot;img-fluid ITC-image common-image-component lazyloaded&quot;]</value>
      <webElementGuid>181c9e7b-30d6-49b3-b217-e69cb6f521b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homepage-SHOP_LC']/div/div/div/div[6]/div/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>845b287a-9e90-449c-a78f-68dc297ee069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='$1 Auctions Cat1']</value>
      <webElementGuid>a26f6209-7606-446b-9cf6-e3e1fb9276ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>879fd6d7-a987-46fa-970b-f501eab17585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '$1 Auctions Cat1' and @title = '$1 Auctions ' and @src = 'https://image.shoplc.com/Banners/June2024/08.06/C1.jpg']</value>
      <webElementGuid>b84e03b9-0bc1-418d-a1c1-5d8f35e8592f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
